# Generated by Django 3.2 on 2024-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='password',
            field=models.CharField(
                default='aboba', max_length=128, verbose_name='password'
            ),
            preserve_default=False,
        ),
    ]
