# Generated by Django 3.2 on 2024-03-11 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yamdbuser',
            options={'ordering': ('email',)},
        ),
    ]
