# Generated by Django 3.2 on 2024-03-11 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0002_alter_yamdbuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='password',
        ),
    ]
