# Generated by Django 3.2 on 2024-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0002_yamdbuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.TextField(
                blank=True, default='', verbose_name='Биография'
            ),
            preserve_default=False,
        ),
    ]
