# Generated by Django 3.2 on 2024-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0003_remove_yamdbuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='password',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
