# Generated by Django 3.2 on 2024-03-11 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0004_yamdbuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='password',
        ),
    ]
