# Generated by Django 3.2 on 2024-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('yamdb_user', '0005_remove_yamdbuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='confirmation_code',
        ),
    ]
