# Generated by Django 3.2 on 2024-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Описание'
            ),
        ),
    ]
