# Generated by Django 3.2 on 2024-03-13 13:59

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name='Год публикации',
            ),
        ),
    ]
