# Generated by Django 3.2 on 2024-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0002_auto_20240304_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, username='me'),
                name='username_me_banned_word',
            ),
        ),
    ]
