# Generated by Django 3.2 on 2024-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
