# Generated by Django 3.2 on 2024-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0005_auto_20240305_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(
                default=123, max_length=128, verbose_name='password'
            ),
            preserve_default=False,
        ),
    ]
