# Generated by Django 3.2 on 2024-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0006_auto_20240305_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(
                blank=True, null=True, verbose_name='Биография'
            ),
        ),
    ]
