# Generated by Django 3.2 on 2024-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0007_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
