# Generated by Django 3.2 on 2024-03-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
